### ISSUE TITLE
"Call to undefined method Winter\Storm\Halcyon\Builder::where()" error

### ISSUE THREAD

**Issue by steva82** [wintercms/wn-search-plugin#3]
Hi, I have this situation:
- winter cms 1.2.1
- Builder 2.0.6
- Pages 2.0.2
- Translate 2.1.0

I have created a custom Model by Builder and it is accurately searchable (adding the component to the layout).

Then, in the component settings, I have checked "Static Page" handler in order to search my static pages by title, but I have this error:

> "Call to undefined method Winter\Storm\Halcyon\Builder::where()" on line 790 of /Applications/MAMP/htdocs/cds/vendor/winter/storm/src/Halcyon/Builder.php

![Screenshot](https://user-images.githubusercontent.com/5539113/218473278-02d49993-2a9a-4d9f-8e6f-c1e865cb3845.jpg)

I have tried to debug inside the file "/plugins/winter/search/components/Search.php" and the problem seems to be here (line 193):

> if (is_callable($class)) {
                $results = $class()->doSearch($query)->paginate($this->property('perPage', 20), 'page', ($handlerPage === $id) ? $page : 1);
            } else {
                $results = $class->doSearch($query)->paginate($this->property('perPage', 20), 'page', ($handlerPage === $id) ? $page : 1);
            }

What could I do to search Static Pages?
Thanks in advanced.

Ste

**Comment by steva82** [comment]
Hi, I have tried a more simple way in order to use the "Search" plugin:
1. I have installed a new clean Winter instance by composer
2. I have added the "Search" plugin
3. I have created a new CMS page
4. I have added the "Search" component to the default layout and I selected "CMS Pages" as Search handler 
5. If a open the website ad try to search a CMS page there is the same error 

> "Call to undefined method Winter\Storm\Halcyon\Builder::where()" on line 790 of /Applications/MAMP/htdocs/canc/vendor/winter/storm/src/Halcyon/Builder.php


Reading the documentation, there are no tasks to do related to CMS Pages (Static Pages and Blog, too). 

I discovered Artisan has some specific commands related to Search and I executed:
`php artisan search:import "\Cms\Classes\Page"`
but even in this case the error appears.

Any suggestion?
Thanks again.



![Screenshot1](https://user-images.githubusercontent.com/5539113/218983823-c5d9aa02-2e97-47bc-8969-02f69342dad1.jpg)

**Comment by bennothommo** [comment]
The Search plugin is still in active development, so there's probably some bugs left in it, like this one.

The issue is simply that Halcyon doesn't have a query builder quite like the normal Eloquent query builder, because it's file based and not using a database.

You should have a more thorough backtrace of the issue either in the Event logs in the Backend, or in the `storage/logs/system.log` file. If you can get us a backtrace, it might give a better indication of where to look further into this.

**Comment by bennothommo** [comment]
Thanks @steva82 - that helps a lot!

I can't promise any timeframes, but we will look into this.

**Comment by steva82** [comment]
Hi @bennothommo , any news?
Thanks.

**Comment by spanjaan** [comment]
Hi @bennothommo ,
i found also same issue.
when you solve this issue?

Thank you.

**Comment by bennothommo** [comment]
@spanjaan @steva82 I have done some preliminary work on this in #4. Would you mind testing this and letting me know if you encounter any issues? You can either swap out the version in Composer:

```
"winter/wn-search-plugin": "dev-fix/halcyon-search"
```

Or just apply the changes directly to the modified files.

**Comment by steva82** [comment]
Hi @bennothommo , it seems to work, thanks!
I hope @spanjaan can confirm...

Can you could tell us how and when us your custom Artisan commands? In the "console" folder there are 4 scripts and , maybe, 2 of them are empty. 
Thanks again.

**Comment by bennothommo** [comment]
@steva82 the console commands are mainly used when you use a separate index service for model records, like ElasticSearch, Algolia or Meilisearch. They allow you to manipulate and pre-index all model records in this external service.

If you use the default database search in the Search plugin, they don't need to be used.

**Comment by steva82** [comment]
Hi @bennothommo ,
sorry for the delay.
I am trying to improve my new website with your plugin.


I prepared my model (Feed.php) with :

- `Winter\Search\Behaviors\Searchable` behavior
- `$searchable` property  

I edit my Plugin.php with the `registerSearchHandlers` method.

Now, I have some difficulties to custom the search field and the "results" page. I mean, you have a single component related to the search form and I copied that html code (default.htm and form.htm) in my template:
```
{{ form_ajax(__SELF__ ~ '::onSearch') }}
    <div class="search-input">
     <input type="text" name="query" class="search-control" placeholder="{{ 'Enter your search query'|trans }}" />
        </div>
       <div class="search-actions">
     <input type="submit" class="search-submit" value="{{ 'Search'|trans }}">
         </div>
  {{ form_close() }}
```



 but I need to see the results in a different page. How can I edit the `form_ajax` parameters?

Thank you.

**Comment by steva82** [comment]
> I take it to mean that you would like the results of the search to appear on a new page as opposed to being loaded via AJAX into the current page?

Yes, correct.




> I will make a note to allow this in a future version.

I hope it will be possible, I really appreciate your effort and help, thank you.
